### ISSUE TITLE
Please add proper error handling for redis server.

### ISSUE THREAD

**Issue by jwangsadinata** [carlomedina/kings-cup#1]
I encountered this when I was hacking your app a little, maybe throw this as an exception and consider handling in properly? Are you only using redis for persistence?

```
null joined channel null
node_redis: Deprecated: The LPUSH command contains a "null" argument.
This is converted to a "null" string now and will return an error from v.3.0 on.
Please handle this in your code to make sure everything works as you intended it to.
A client disconnected
```

**Comment by carlomedina** [comment]
Hi Jason, the error was a legitimate error. Thanks for pointing it out. It should be fixed with the latest commit. Great to hear you master!
